[package]
name = "bible-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.12"  # For HTML scraping
serde_json = "1.0"  # For JSON serialization
select = "0.5"